### PR TITLE
Fixes #15673 - changes pulp df to use -P (POSIX) output

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by shlomizadok** [comment]
Please use this instead of #6

**Comment by ohadlevy** [comment]
note you are missing test changes.

**Comment by shlomizadok** [comment]
No need for test changes as the API returns same keys :)

**Comment by lzap** [comment]
I don't have concerns, generally :+1: but there is a bug we should fix. The label changes according to the block size input:

```
[root@fsix ~]# df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/vda3        4512416 1106748   3169792  26% /
tmpfs            1542588       0   1542588   0% /dev/shm
/dev/vda1         499656   30700    442744   7% /boot
[root@fsix ~]# df -P
Filesystem     1024-blocks    Used Available Capacity Mounted on
/dev/vda3          4512416 1106748   3169792      26% /
tmpfs              1542588       0   1542588       0% /dev/shm
/dev/vda1           499656   30700    442744       7% /boot
[root@fsix ~]# df -P -B1048576
Filesystem     1048576-blocks  Used Available Capacity Mounted on
/dev/vda3                4407  1081      3096      26% /
tmpfs                    1507     0      1507       0% /dev/shm
/dev/vda1                 488    30       433       7% /boot
```

It was not introduced by this patch, I just noticed it.

**Comment by ohadlevy** [comment]
@lzap can you open a separate issue for this? i guess we can just use the size instead of hard code 1024, but it exists also before.

**Comment by ohadlevy** [comment]
since there is no jenkins configured - please paste the output of rake tests, when i run it myself i have more than 10 failures which i think is something in my env.

**Comment by ohadlevy** [comment]
also, sinatra should not return html on json request when they fail, maybe something similar to http://stackoverflow.com/questions/8772641/how-to-define-global-error-handler-for-json-in-sinatra. /cc @witlessbird

**Comment by shlomizadok** [comment]
Test results:
```bash
szadok:smart-proxy-pulp/ (refs_14894) $ bundle exec rake test                                                                                                                                           [11:22:15]
/usr/bin/ruby -I"lib:.:lib:test" -I"/home/szadok/.gem/ruby/gems/rake-10.5.0/lib" "/home/szadok/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/disk_usage_test.rb" "test/pulp_api_test.rb" 
Loaded suite /home/szadok/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader
Started
..............

Finished in 0.053417573 seconds.

14 tests, 20 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

262.09 tests/s, 374.41 assertions/s
```

How do I add this to Jenkins?

**Comment by ohadlevy** [comment]
merged as 71b1a3b thanks @shlomizadok

**Comment by lzap** [comment]
Created http://projects.theforeman.org/issues/15686

**Pull request closed without merging**
